function createfigureforvaryingk(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 13-May-2020 13:32:59

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3,'Parent',axes1,'MarkerSize',8);
set(plot1(1),'DisplayName','alg1','Marker','o');
set(plot1(2),'DisplayName','alg2','Marker','*','MarkerSize',6);
set(plot1(3),'DisplayName','greedy train','Marker','x');
set(plot1(4),'DisplayName','greedy test','Marker','diamond');
set(plot1(5),'DisplayName','  random meta greedy test','Marker','+');

% Create ylabel
ylabel('function value','FontName','Times New Roman');

% Create xlabel
xlabel({'k'},'FontName','Times New Roman');

% Create title
title({'l= 0.8k'},'FontSize',20);

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',16);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.64951768488746 0.18839542147549 0.188106721788394 0.164655172413793],...
    'FontSize',20);

