function createfigurecvaryl_withrandom(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Jun-2020 15:19:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerSize',15,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','Train Greedy','Marker','x');
set(plot1(2),'DisplayName','Random set','Marker','+');
set(plot1(3),'DisplayName','meta-Greedy alg2','MarkerSize',10,...
    'Marker','diamond',...
    'Color',[1 0 0]);
set(plot1(4),'DisplayName','meta-Greedy alg1','Marker','.',...
    'Color',[0.929411768913269 0.694117665290833 0.125490203499794]);
set(plot1(5),'DisplayName','Random meta-Greedy','Marker','*');
set(plot1(6),'DisplayName','Test Greedy','Marker','square',...
    'Color',[0.749019622802734 0 0.749019622802734]);

% Create ylabel
ylabel('Objective Value');

% Create xlabel
xlabel('l');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[5 18]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.75 0.98]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',20);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.551724137931034 0.17696826853121 0.304376657824933 0.181118881118881]);
set(legend1,'color','none');

