all:  rideshare rideshare1 ridesharevaryk ridesharevarl
rideshare: rideshare.c
	gcc -o rideshare rideshare.c -lm -O3	
rideshare1: rideshare1.c
	gcc -o rideshare1 rideshare1.c -lm -O3
ridesharevaryk: ridesharevaryk.c
	gcc -o ridesharevaryk ridesharevaryk.c -lm -O3
ridesharevarl: ridesharevaryl.c
	gcc -o ridesharevaryl ridesharevaryl.c -lm -O3
